export const INVITE_CODE = 'VM2026';
export const ADMIN_CODE  = 'ADMIN2026';
export const FD_API_KEY  = 'YOUR_KEY_HERE';

export const GROUPS = {
  A: ['Mexico',     'Sør-Afrika',  'Sør-Korea',    'Tsjekkia'],
  B: ['Canada',     'Bosnia-Herz', 'Qatar',        'Sveits'],
  C: ['Brasil',     'Marokko',     'Haiti',        'Skottland'],
  D: ['USA',        'Paraguay',    'Australia',    'Tyrkia'],
  E: ['Tyskland',   'Curacao',     'Elfenbenskysten','Ecuador'],
  F: ['Nederland',  'Japan',       'Sverige',      'Tunisia'],
  G: ['Belgia',     'Egypt',       'Iran',         'New Zealand'],
  H: ['Spania',     'Kapp Verde',  'Saudi-Arabia', 'Uruguay'],
  I: ['Frankrike',  'Senegal',     'Irak',         'Norge'],
  J: ['Argentina',  'Algerie',     'Østerrike',    'Jordan'],
  K: ['Portugal',   'Kongo DR',    'Usbekistan',   'Colombia'],
  L: ['England',    'Kroatia',     'Ghana',        'Panama'],
};

export const ALL_TEAMS = [...new Set(Object.values(GROUPS).flat())].sort();

export const STADIUMS = {
  azteca:       { name: 'Estadio Azteca',              city: 'Mexico City',              country: 'Mexico',  img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6e/Azteca_Interior_2009.jpg/640px-Azteca_Interior_2009.jpg' },
  akron:        { name: 'Estadio Akron',               city: 'Zapopan (Guadalajara)',    country: 'Mexico',  img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e4/Estadio_Akron_panorama.jpg/640px-Estadio_Akron_panorama.jpg' },
  bbva:         { name: 'Estadio BBVA',                city: 'Monterrey',                country: 'Mexico',  img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4d/Estadio_BBVA_Bancomer.jpg/640px-Estadio_BBVA_Bancomer.jpg' },
  bmo:          { name: 'BMO Field',                   city: 'Toronto',                  country: 'Canada',  img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/64/BMO_Field_September_2016.jpg/640px-BMO_Field_September_2016.jpg' },
  bcplace:      { name: 'BC Place',                    city: 'Vancouver',                country: 'Canada',  img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b1/BC_Place_Vancouver.jpg/640px-BC_Place_Vancouver.jpg' },
  sofi:         { name: 'SoFi Stadium',                city: 'Inglewood (Los Angeles)',  country: 'USA',     img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/66/SoFi_Stadium_2020.jpg/640px-SoFi_Stadium_2020.jpg' },
  levis:        { name: "Levi's Stadium",              city: 'Santa Clara (San Francisco)', country: 'USA',  img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6b/Levi%27s_Stadium_from_the_north.jpg/640px-Levi%27s_Stadium_from_the_north.jpg' },
  metlife:      { name: 'MetLife Stadium',             city: 'East Rutherford (New York)', country: 'USA',   img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a3/MetLife_Stadium_-_New_Jersey.jpg/640px-MetLife_Stadium_-_New_Jersey.jpg' },
  gillette:     { name: 'Gillette Stadium',            city: 'Foxborough (Boston)',       country: 'USA',    img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a5/Gillette_Stadium_at_Night.jpg/640px-Gillette_Stadium_at_Night.jpg' },
  att:          { name: 'AT&T Stadium',               city: 'Arlington (Dallas)',         country: 'USA',    img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/af/Cowboys_Stadium_Exterior.jpg/640px-Cowboys_Stadium_Exterior.jpg' },
  nrg:          { name: 'NRG Stadium',                city: 'Houston',                    country: 'USA',    img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3e/NRG_Stadium_Houston.jpg/640px-NRG_Stadium_Houston.jpg' },
  linc:         { name: 'Lincoln Financial Field',    city: 'Philadelphia',               country: 'USA',    img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/65/Lincoln_Financial_Field_2014.jpg/640px-Lincoln_Financial_Field_2014.jpg' },
  mercedesbenz: { name: 'Mercedes-Benz Stadium',      city: 'Atlanta',                    country: 'USA',    img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a6/Mercedes-Benz_Stadium_interior.jpg/640px-Mercedes-Benz_Stadium_interior.jpg' },
  lumen:        { name: 'Lumen Field',                city: 'Seattle',                    country: 'USA',    img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1e/Lumen_Field_2021.jpg/640px-Lumen_Field_2021.jpg' },
  hardrock:     { name: 'Hard Rock Stadium',          city: 'Miami Gardens (Miami)',       country: 'USA',    img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/29/Hard_Rock_Stadium_2021.jpg/640px-Hard_Rock_Stadium_2021.jpg' },
  arrowhead:    { name: 'Arrowhead Stadium',          city: 'Kansas City',                country: 'USA',    img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c7/Arrowhead_stadium.jpg/640px-Arrowhead_stadium.jpg' },
};

// All times in CEST (Central European Summer Time = ET + 6h)
export const GROUP_MATCHES = [
  { id:'A1', group:'A', home:'Mexico',    away:'Sør-Afrika', phase:'group', date:'2026-06-11', time:'21:00', stadium:'azteca' },
  { id:'A2', group:'A', home:'Sør-Korea', away:'Tsjekkia',   phase:'group', date:'2026-06-12', time:'04:00', stadium:'akron' },
  { id:'A3', group:'A', home:'Tsjekkia',  away:'Sør-Afrika', phase:'group', date:'2026-06-18', time:'18:00', stadium:'mercedesbenz' },
  { id:'A4', group:'A', home:'Mexico',    away:'Sør-Korea',  phase:'group', date:'2026-06-19', time:'03:00', stadium:'akron' },
  { id:'A5', group:'A', home:'Tsjekkia',  away:'Mexico',     phase:'group', date:'2026-06-25', time:'03:00', stadium:'azteca' },
  { id:'A6', group:'A', home:'Sør-Afrika',away:'Sør-Korea',  phase:'group', date:'2026-06-25', time:'03:00', stadium:'bbva' },
  { id:'B1', group:'B', home:'Canada',    away:'Bosnia-Herz',phase:'group', date:'2026-06-12', time:'21:00', stadium:'bmo' },
  { id:'B2', group:'B', home:'Qatar',     away:'Sveits',     phase:'group', date:'2026-06-13', time:'21:00', stadium:'levis' },
  { id:'B3', group:'B', home:'Sveits',    away:'Bosnia-Herz',phase:'group', date:'2026-06-18', time:'21:00', stadium:'sofi' },
  { id:'B4', group:'B', home:'Canada',    away:'Qatar',      phase:'group', date:'2026-06-19', time:'00:00', stadium:'bcplace' },
  { id:'B5', group:'B', home:'Sveits',    away:'Canada',     phase:'group', date:'2026-06-25', time:'21:00', stadium:'bcplace' },
  { id:'B6', group:'B', home:'Bosnia-Herz',away:'Qatar',     phase:'group', date:'2026-06-25', time:'21:00', stadium:'lumen' },
  { id:'C1', group:'C', home:'Brasil',    away:'Marokko',    phase:'group', date:'2026-06-14', time:'00:00', stadium:'metlife' },
  { id:'C2', group:'C', home:'Haiti',     away:'Skottland',  phase:'group', date:'2026-06-14', time:'03:00', stadium:'gillette' },
  { id:'C3', group:'C', home:'Skottland', away:'Marokko',    phase:'group', date:'2026-06-20', time:'00:00', stadium:'gillette' },
  { id:'C4', group:'C', home:'Brasil',    away:'Haiti',      phase:'group', date:'2026-06-20', time:'02:30', stadium:'linc' },
  { id:'C5', group:'C', home:'Skottland', away:'Brasil',     phase:'group', date:'2026-06-25', time:'00:00', stadium:'hardrock' },
  { id:'C6', group:'C', home:'Marokko',   away:'Haiti',      phase:'group', date:'2026-06-25', time:'00:00', stadium:'mercedesbenz' },
  { id:'D1', group:'D', home:'USA',       away:'Paraguay',   phase:'group', date:'2026-06-13', time:'03:00', stadium:'sofi' },
  { id:'D2', group:'D', home:'Australia', away:'Tyrkia',     phase:'group', date:'2026-06-14', time:'06:00', stadium:'bcplace' },
  { id:'D3', group:'D', home:'USA',       away:'Australia',  phase:'group', date:'2026-06-19', time:'21:00', stadium:'lumen' },
  { id:'D4', group:'D', home:'Tyrkia',    away:'Paraguay',   phase:'group', date:'2026-06-20', time:'05:00', stadium:'levis' },
  { id:'D5', group:'D', home:'Tyrkia',    away:'USA',        phase:'group', date:'2026-06-26', time:'04:00', stadium:'sofi' },
  { id:'D6', group:'D', home:'Paraguay',  away:'Australia',  phase:'group', date:'2026-06-26', time:'04:00', stadium:'levis' },
  { id:'E1', group:'E', home:'Tyskland',  away:'Curacao',    phase:'group', date:'2026-06-14', time:'19:00', stadium:'nrg' },
  { id:'E2', group:'E', home:'Elfenbenskysten',away:'Ecuador',phase:'group',date:'2026-06-15', time:'01:00', stadium:'linc' },
  { id:'E3', group:'E', home:'Tyskland',  away:'Elfenbenskysten',phase:'group',date:'2026-06-21',time:'22:00',stadium:'bmo' },
  { id:'E4', group:'E', home:'Ecuador',   away:'Curacao',    phase:'group', date:'2026-06-21', time:'02:00', stadium:'arrowhead' },
  { id:'E5', group:'E', home:'Curacao',   away:'Elfenbenskysten',phase:'group',date:'2026-06-26',time:'22:00',stadium:'linc' },
  { id:'E6', group:'E', home:'Ecuador',   away:'Tyskland',   phase:'group', date:'2026-06-26', time:'22:00', stadium:'metlife' },
  { id:'F1', group:'F', home:'Nederland', away:'Japan',      phase:'group', date:'2026-06-14', time:'22:00', stadium:'att' },
  { id:'F2', group:'F', home:'Sverige',   away:'Tunisia',    phase:'group', date:'2026-06-15', time:'04:00', stadium:'bbva' },
  { id:'F3', group:'F', home:'Nederland', away:'Sverige',    phase:'group', date:'2026-06-20', time:'19:00', stadium:'nrg' },
  { id:'F4', group:'F', home:'Tunisia',   away:'Japan',      phase:'group', date:'2026-06-22', time:'06:00', stadium:'bbva' },
  { id:'F5', group:'F', home:'Japan',     away:'Sverige',    phase:'group', date:'2026-06-26', time:'01:00', stadium:'att' },
  { id:'F6', group:'F', home:'Tunisia',   away:'Nederland',  phase:'group', date:'2026-06-26', time:'01:00', stadium:'arrowhead' },
  { id:'G1', group:'G', home:'Belgia',    away:'Egypt',      phase:'group', date:'2026-06-15', time:'21:00', stadium:'lumen' },
  { id:'G2', group:'G', home:'Iran',      away:'New Zealand',phase:'group', date:'2026-06-16', time:'03:00', stadium:'sofi' },
  { id:'G3', group:'G', home:'Belgia',    away:'Iran',       phase:'group', date:'2026-06-21', time:'21:00', stadium:'sofi' },
  { id:'G4', group:'G', home:'New Zealand',away:'Egypt',     phase:'group', date:'2026-06-22', time:'03:00', stadium:'bcplace' },
  { id:'G5', group:'G', home:'Egypt',     away:'Iran',       phase:'group', date:'2026-06-27', time:'05:00', stadium:'lumen' },
  { id:'G6', group:'G', home:'New Zealand',away:'Belgia',    phase:'group', date:'2026-06-27', time:'05:00', stadium:'bcplace' },
  { id:'H1', group:'H', home:'Spania',    away:'Kapp Verde', phase:'group', date:'2026-06-15', time:'18:00', stadium:'mercedesbenz' },
  { id:'H2', group:'H', home:'Saudi-Arabia',away:'Uruguay',  phase:'group', date:'2026-06-16', time:'00:00', stadium:'hardrock' },
  { id:'H3', group:'H', home:'Spania',    away:'Saudi-Arabia',phase:'group',date:'2026-06-21', time:'18:00', stadium:'mercedesbenz' },
  { id:'H4', group:'H', home:'Uruguay',   away:'Kapp Verde', phase:'group', date:'2026-06-22', time:'00:00', stadium:'hardrock' },
  { id:'H5', group:'H', home:'Kapp Verde',away:'Saudi-Arabia',phase:'group',date:'2026-06-27', time:'02:00', stadium:'nrg' },
  { id:'H6', group:'H', home:'Uruguay',   away:'Spania',     phase:'group', date:'2026-06-27', time:'02:00', stadium:'akron' },
  { id:'I1', group:'I', home:'Frankrike', away:'Senegal',    phase:'group', date:'2026-06-16', time:'21:00', stadium:'metlife' },
  { id:'I2', group:'I', home:'Irak',      away:'Norge',      phase:'group', date:'2026-06-17', time:'00:00', stadium:'gillette' },
  { id:'I3', group:'I', home:'Frankrike', away:'Irak',       phase:'group', date:'2026-06-22', time:'23:00', stadium:'linc' },
  { id:'I4', group:'I', home:'Norge',     away:'Senegal',    phase:'group', date:'2026-06-23', time:'02:00', stadium:'metlife' },
  { id:'I5', group:'I', home:'Norge',     away:'Frankrike',  phase:'group', date:'2026-06-27', time:'21:00', stadium:'gillette' },
  { id:'I6', group:'I', home:'Senegal',   away:'Irak',       phase:'group', date:'2026-06-27', time:'21:00', stadium:'bmo' },
  { id:'J1', group:'J', home:'Argentina', away:'Algerie',    phase:'group', date:'2026-06-17', time:'03:00', stadium:'arrowhead' },
  { id:'J2', group:'J', home:'Østerrike', away:'Jordan',     phase:'group', date:'2026-06-18', time:'06:00', stadium:'levis' },
  { id:'J3', group:'J', home:'Argentina', away:'Østerrike',  phase:'group', date:'2026-06-22', time:'19:00', stadium:'att' },
  { id:'J4', group:'J', home:'Jordan',    away:'Algerie',    phase:'group', date:'2026-06-23', time:'05:00', stadium:'levis' },
  { id:'J5', group:'J', home:'Jordan',    away:'Argentina',  phase:'group', date:'2026-06-28', time:'04:00', stadium:'att' },
  { id:'J6', group:'J', home:'Algerie',   away:'Østerrike',  phase:'group', date:'2026-06-28', time:'04:00', stadium:'arrowhead' },
  { id:'K1', group:'K', home:'Portugal',  away:'Kongo DR',   phase:'group', date:'2026-06-17', time:'19:00', stadium:'nrg' },
  { id:'K2', group:'K', home:'Usbekistan',away:'Colombia',   phase:'group', date:'2026-06-18', time:'04:00', stadium:'azteca' },
  { id:'K3', group:'K', home:'Portugal',  away:'Usbekistan', phase:'group', date:'2026-06-23', time:'19:00', stadium:'nrg' },
  { id:'K4', group:'K', home:'Colombia',  away:'Kongo DR',   phase:'group', date:'2026-06-24', time:'04:00', stadium:'akron' },
  { id:'K5', group:'K', home:'Colombia',  away:'Portugal',   phase:'group', date:'2026-06-28', time:'01:30', stadium:'hardrock' },
  { id:'K6', group:'K', home:'Kongo DR',  away:'Usbekistan', phase:'group', date:'2026-06-28', time:'01:30', stadium:'mercedesbenz' },
  { id:'L1', group:'L', home:'England',   away:'Kroatia',    phase:'group', date:'2026-06-17', time:'22:00', stadium:'att' },
  { id:'L2', group:'L', home:'Ghana',     away:'Panama',     phase:'group', date:'2026-06-18', time:'01:00', stadium:'bmo' },
  { id:'L3', group:'L', home:'England',   away:'Ghana',      phase:'group', date:'2026-06-23', time:'22:00', stadium:'gillette' },
  { id:'L4', group:'L', home:'Panama',    away:'Kroatia',    phase:'group', date:'2026-06-24', time:'01:00', stadium:'bmo' },
  { id:'L5', group:'L', home:'Panama',    away:'England',    phase:'group', date:'2026-06-27', time:'23:00', stadium:'metlife' },
  { id:'L6', group:'L', home:'Kroatia',   away:'Ghana',      phase:'group', date:'2026-06-27', time:'23:00', stadium:'linc' },
];

export const KNOCKOUT_ROUNDS = [
  { phase:'r32',    label:'Sekstendelsfinalene (kamp 73–88)', count:16 },
  { phase:'r16',    label:'Åttendedelsfinalene (kamp 89–96)', count:8  },
  { phase:'qf',     label:'Kvartfinalene (kamp 97–100)',       count:4  },
  { phase:'sf',     label:'Semifinalene (kamp 101–102)',       count:2  },
  { phase:'bronze', label:'Bronsefinalen (kamp 103)',          count:1  },
  { phase:'final',  label:'Gullfinalen (kamp 104)',            count:1  },
];

export const KNOCKOUT_MATCHES = [
  { id:'r32_1',  phase:'r32',    matchNum:73,  home:'Toer A',         away:'Toer B',           date:'2026-06-28', time:'21:00', stadium:'sofi' },
  { id:'r32_2',  phase:'r32',    matchNum:74,  home:'Vinner E',       away:'3er A/B/C/D/F',    date:'2026-06-29', time:'22:30', stadium:'gillette' },
  { id:'r32_3',  phase:'r32',    matchNum:75,  home:'Vinner F',       away:'Toer C',           date:'2026-06-30', time:'03:00', stadium:'bbva' },
  { id:'r32_4',  phase:'r32',    matchNum:76,  home:'Vinner C',       away:'Toer F',           date:'2026-06-29', time:'19:00', stadium:'nrg' },
  { id:'r32_5',  phase:'r32',    matchNum:77,  home:'Vinner I',       away:'3er C/D/F/G/H',    date:'2026-06-30', time:'23:00', stadium:'metlife' },
  { id:'r32_6',  phase:'r32',    matchNum:78,  home:'Toer E',         away:'Toer I',           date:'2026-06-30', time:'19:00', stadium:'att' },
  { id:'r32_7',  phase:'r32',    matchNum:79,  home:'Vinner A',       away:'3er C/E/F/H/I',    date:'2026-07-01', time:'03:00', stadium:'azteca' },
  { id:'r32_8',  phase:'r32',    matchNum:80,  home:'Vinner L',       away:'3er E/H/I/J/K',    date:'2026-07-01', time:'18:00', stadium:'mercedesbenz' },
  { id:'r32_9',  phase:'r32',    matchNum:81,  home:'Vinner D',       away:'3er B/E/F/I/J',    date:'2026-07-02', time:'02:00', stadium:'levis' },
  { id:'r32_10', phase:'r32',    matchNum:82,  home:'Vinner G',       away:'3er A/E/H/I/J',    date:'2026-07-01', time:'22:00', stadium:'lumen' },
  { id:'r32_11', phase:'r32',    matchNum:83,  home:'Toer K',         away:'Toer L',           date:'2026-07-03', time:'01:00', stadium:'bmo' },
  { id:'r32_12', phase:'r32',    matchNum:84,  home:'Vinner H',       away:'Toer J',           date:'2026-07-02', time:'21:00', stadium:'sofi' },
  { id:'r32_13', phase:'r32',    matchNum:85,  home:'Vinner B',       away:'3er E/F/G/I/J',    date:'2026-07-03', time:'05:00', stadium:'bcplace' },
  { id:'r32_14', phase:'r32',    matchNum:86,  home:'Vinner J',       away:'Toer H',           date:'2026-07-04', time:'00:00', stadium:'hardrock' },
  { id:'r32_15', phase:'r32',    matchNum:87,  home:'Vinner K',       away:'3er D/E/I/J/L',    date:'2026-07-04', time:'03:30', stadium:'arrowhead' },
  { id:'r32_16', phase:'r32',    matchNum:88,  home:'Toer D',         away:'Toer G',           date:'2026-07-03', time:'20:00', stadium:'att' },
  { id:'r16_1',  phase:'r16',    matchNum:89,  home:'Vinner kamp 74', away:'Vinner kamp 77',   date:'2026-07-04', time:'23:00', stadium:'linc' },
  { id:'r16_2',  phase:'r16',    matchNum:90,  home:'Vinner kamp 73', away:'Vinner kamp 75',   date:'2026-07-04', time:'19:00', stadium:'nrg' },
  { id:'r16_3',  phase:'r16',    matchNum:91,  home:'Vinner kamp 76', away:'Vinner kamp 78',   date:'2026-07-05', time:'22:00', stadium:'metlife' },
  { id:'r16_4',  phase:'r16',    matchNum:92,  home:'Vinner kamp 79', away:'Vinner kamp 80',   date:'2026-07-06', time:'02:00', stadium:'azteca' },
  { id:'r16_5',  phase:'r16',    matchNum:93,  home:'Vinner kamp 83', away:'Vinner kamp 84',   date:'2026-07-06', time:'21:00', stadium:'att' },
  { id:'r16_6',  phase:'r16',    matchNum:94,  home:'Vinner kamp 81', away:'Vinner kamp 82',   date:'2026-07-07', time:'02:00', stadium:'lumen' },
  { id:'r16_7',  phase:'r16',    matchNum:95,  home:'Vinner kamp 86', away:'Vinner kamp 88',   date:'2026-07-07', time:'18:00', stadium:'mercedesbenz' },
  { id:'r16_8',  phase:'r16',    matchNum:96,  home:'Vinner kamp 85', away:'Vinner kamp 87',   date:'2026-07-07', time:'22:00', stadium:'bcplace' },
  { id:'qf_1',   phase:'qf',     matchNum:97,  home:'Vinner kamp 89', away:'Vinner kamp 90',   date:'2026-07-09', time:'22:00', stadium:'gillette' },
  { id:'qf_2',   phase:'qf',     matchNum:98,  home:'Vinner kamp 93', away:'Vinner kamp 94',   date:'2026-07-10', time:'21:00', stadium:'sofi' },
  { id:'qf_3',   phase:'qf',     matchNum:99,  home:'Vinner kamp 91', away:'Vinner kamp 92',   date:'2026-07-11', time:'23:00', stadium:'hardrock' },
  { id:'qf_4',   phase:'qf',     matchNum:100, home:'Vinner kamp 95', away:'Vinner kamp 96',   date:'2026-07-12', time:'03:00', stadium:'arrowhead' },
  { id:'sf_1',   phase:'sf',     matchNum:101, home:'Vinner kamp 97', away:'Vinner kamp 98',   date:'2026-07-14', time:'21:00', stadium:'att' },
  { id:'sf_2',   phase:'sf',     matchNum:102, home:'Vinner kamp 99', away:'Vinner kamp 100',  date:'2026-07-15', time:'21:00', stadium:'mercedesbenz' },
  { id:'bronze', phase:'bronze', matchNum:103, home:'Taper kamp 101', away:'Taper kamp 102',   date:'2026-07-18', time:'23:00', stadium:'hardrock' },
  { id:'final',  phase:'final',  matchNum:104, home:'Vinner kamp 101',away:'Vinner kamp 102',  date:'2026-07-19', time:'21:00', stadium:'metlife' },
];

export const PHASE_OPTIONS = [
  { value:'pre',         label:'🕐 Før turnering – åpent for alle tips' },
  { value:'group_lock',  label:'🔒 Gruppespill startet – stengt' },
  { value:'group_done',  label:'✅ Gruppespill ferdig – endre sluttspill' },
  { value:'r32_lock',    label:'🔒 16-delsfinaler startet – stengt' },
  { value:'r32_done',    label:'✅ 16-delsfinaler ferdig' },
  { value:'r16_lock',    label:'🔒 8-delsfinaler startet – stengt' },
  { value:'r16_done',    label:'✅ 8-delsfinaler ferdig' },
  { value:'qf_lock',     label:'🔒 Kvartfinaler startet – stengt' },
  { value:'qf_done',     label:'✅ Kvartfinaler ferdig' },
  { value:'sf_lock',     label:'🔒 Semifinaler startet – stengt' },
  { value:'sf_done',     label:'✅ Semifinaler ferdig' },
  { value:'bronze_lock', label:'🔒 Finaler startet – stengt' },
  { value:'finished',    label:'🏆 Turnering avsluttet' },
];

export const OPEN_PHASES = new Set(['pre','group_done','r32_done','r16_done','qf_done','sf_done']);

export const FLAGS = {
  'Argentina':'🇦🇷','Algerie':'🇩🇿','Australia':'🇦🇺','Belgia':'🇧🇪',
  'Bolivia':'🇧🇴','Bosnia-Herz':'🇧🇦','Brasil':'🇧🇷','Canada':'🇨🇦',
  'Chile':'🇨🇱','Colombia':'🇨🇴','Costa Rica':'🇨🇷','Curacao':'🇨🇼',
  'Ecuador':'🇪🇨','Elfenbenskysten':'🇨🇮','Egypt':'🇪🇬','England':'🏴󠁧󠁢󠁥󠁮󠁧󠁿',
  'Frankrike':'🇫🇷','Tyskland':'🇩🇪','Ghana':'🇬🇭','Haiti':'🇭🇹',
  'Honduras':'🇭🇳','Iran':'🇮🇷','Irak':'🇮🇶','Jamaica':'🇯🇲',
  'Japan':'🇯🇵','Jordan':'🇯🇴','Kamerun':'🇨🇲','Kapp Verde':'🇨🇻',
  'Kongo DR':'🇨🇩','Kroatia':'🇭🇷','Marokko':'🇲🇦','Mexico':'🇲🇽',
  'Nederland':'🇳🇱','New Zealand':'🇳🇿','Norge':'🇳🇴','Panama':'🇵🇦',
  'Paraguay':'🇵🇾','Peru':'🇵🇪','Portugal':'🇵🇹','Qatar':'🇶🇦',
  'Saudi-Arabia':'🇸🇦','Senegal':'🇸🇳','Skottland':'🏴󠁧󠁢󠁳󠁣󠁴󠁿','Spania':'🇪🇸',
  'Sveits':'🇨🇭','Sverige':'🇸🇪','Sør-Afrika':'🇿🇦','Sør-Korea':'🇰🇷',
  'Tunisia':'🇹🇳','Tyrkia':'🇹🇷','Tsjekkia':'🇨🇿','USA':'🇺🇸',
  'Uruguay':'🇺🇾','Usbekistan':'🇺🇿',
};

export const WS_MSGS = {
  pre:         { label:'🟢 Åpent – lever dine tips!',            color:'#052e16' },
  group_lock:  { label:'🔴 Stengt – gruppespillet pågår',        color:'#450a0a' },
  group_done:  { label:'🟢 Åpent – endre sluttspill-tips!',      color:'#052e16' },
  r32_lock:    { label:'🔴 Stengt – sekstendelsfinalene pågår',  color:'#450a0a' },
  r32_done:    { label:'🟢 Åpent – oppdater neste runde!',       color:'#052e16' },
  r16_lock:    { label:'🔴 Stengt – åttendedelsfinalene pågår',  color:'#450a0a' },
  r16_done:    { label:'🟢 Åpent – oppdater neste runde!',       color:'#052e16' },
  qf_lock:     { label:'🔴 Stengt – kvartfinalene pågår',        color:'#450a0a' },
  qf_done:     { label:'🟢 Åpent – oppdater semifinale-tips!',   color:'#052e16' },
  sf_lock:     { label:'🔴 Stengt – semifinalene pågår',         color:'#450a0a' },
  sf_done:     { label:'🟢 Åpent – lever finale-tips!',          color:'#052e16' },
  bronze_lock: { label:'🔴 Stengt – finalene pågår',             color:'#450a0a' },
  finished:    { label:'🏁 Turneringen er over!',                color:'#1c1f2e' },
};

export const SPEC_FIELDS = [
  { key:'champion',    label:'🥇 Verdensmester',   pts:25 },
  { key:'runner_up',   label:'🥈 Sølvvinner',       pts:15 },
  { key:'third',       label:'🥉 Bronsevinner',      pts:10 },
  { key:'topscorer',   label:'⚽ Toppscorer',         pts:20 },
  { key:'most_carded', label:'🟨 Mest kort – lag',   pts:10 },
];
