// squads.js – VM 2026 spillerstaller
// Oppdateres med offisielle tropper når FIFA kunngjør disse (medio mai 2026)
// Format: { lag: [{ name, pos }] }
// pos: GK=Keeper, DEF=Forsvar, MID=Midtbane, FWD=Angrep

export const SQUADS = {
  'Argentina': [
    { name: 'Lionel Messi', pos: 'FWD' },
    { name: 'Julián Álvarez', pos: 'FWD' },
    { name: 'Lautaro Martínez', pos: 'FWD' },
    { name: 'Ángel Di María', pos: 'FWD' },
    { name: 'Rodrigo De Paul', pos: 'MID' },
    { name: 'Alexis Mac Allister', pos: 'MID' },
    { name: 'Enzo Fernández', pos: 'MID' },
    { name: 'Nicolás Otamendi', pos: 'DEF' },
    { name: 'Cristian Romero', pos: 'DEF' },
    { name: 'Emiliano Martínez', pos: 'GK' },
  ],
  'Frankrike': [
    { name: 'Kylian Mbappé', pos: 'FWD' },
    { name: 'Antoine Griezmann', pos: 'FWD' },
    { name: 'Olivier Giroud', pos: 'FWD' },
    { name: 'Marcus Thuram', pos: 'FWD' },
    { name: 'Aurélien Tchouaméni', pos: 'MID' },
    { name: 'Adrien Rabiot', pos: 'MID' },
    { name: 'Eduardo Camavinga', pos: 'MID' },
    { name: 'Raphaël Varane', pos: 'DEF' },
    { name: 'Jules Koundé', pos: 'DEF' },
    { name: 'Mike Maignan', pos: 'GK' },
  ],
  'Brasil': [
    { name: 'Vinícius Jr.', pos: 'FWD' },
    { name: 'Rodrygo', pos: 'FWD' },
    { name: 'Richarlison', pos: 'FWD' },
    { name: 'Gabriel Martinelli', pos: 'FWD' },
    { name: 'Lucas Paquetá', pos: 'MID' },
    { name: 'Bruno Guimarães', pos: 'MID' },
    { name: 'Casemiro', pos: 'MID' },
    { name: 'Marquinhos', pos: 'DEF' },
    { name: 'Éder Militão', pos: 'DEF' },
    { name: 'Alisson', pos: 'GK' },
  ],
  'England': [
    { name: 'Harry Kane', pos: 'FWD' },
    { name: 'Bukayo Saka', pos: 'FWD' },
    { name: 'Phil Foden', pos: 'MID' },
    { name: 'Jude Bellingham', pos: 'MID' },
    { name: 'Declan Rice', pos: 'MID' },
    { name: 'Marcus Rashford', pos: 'FWD' },
    { name: 'Raheem Sterling', pos: 'FWD' },
    { name: 'John Stones', pos: 'DEF' },
    { name: 'Kyle Walker', pos: 'DEF' },
    { name: 'Jordan Pickford', pos: 'GK' },
  ],
  'Spania': [
    { name: 'Álvaro Morata', pos: 'FWD' },
    { name: 'Pedri', pos: 'MID' },
    { name: 'Gavi', pos: 'MID' },
    { name: 'Rodri', pos: 'MID' },
    { name: 'Ferran Torres', pos: 'FWD' },
    { name: 'Dani Olmo', pos: 'MID' },
    { name: 'Lamine Yamal', pos: 'FWD' },
    { name: 'Aymeric Laporte', pos: 'DEF' },
    { name: 'Dani Carvajal', pos: 'DEF' },
    { name: 'Unai Simón', pos: 'GK' },
  ],
  'Portugal': [
    { name: 'Cristiano Ronaldo', pos: 'FWD' },
    { name: 'Bruno Fernandes', pos: 'MID' },
    { name: 'Bernardo Silva', pos: 'MID' },
    { name: 'João Félix', pos: 'FWD' },
    { name: 'Rafael Leão', pos: 'FWD' },
    { name: 'Vitinha', pos: 'MID' },
    { name: 'Rúben Neves', pos: 'MID' },
    { name: 'Rúben Dias', pos: 'DEF' },
    { name: 'João Cancelo', pos: 'DEF' },
    { name: 'Diogo Costa', pos: 'GK' },
  ],
  'Tyskland': [
    { name: 'Kai Havertz', pos: 'FWD' },
    { name: 'Leroy Sané', pos: 'FWD' },
    { name: 'Florian Wirtz', pos: 'MID' },
    { name: 'Jamal Musiala', pos: 'MID' },
    { name: 'Joshua Kimmich', pos: 'MID' },
    { name: 'Thomas Müller', pos: 'FWD' },
    { name: 'Toni Kroos', pos: 'MID' },
    { name: 'Antonio Rüdiger', pos: 'DEF' },
    { name: 'David Raum', pos: 'DEF' },
    { name: 'Manuel Neuer', pos: 'GK' },
  ],
  'Nederland': [
    { name: 'Memphis Depay', pos: 'FWD' },
    { name: 'Cody Gakpo', pos: 'FWD' },
    { name: 'Xavi Simons', pos: 'MID' },
    { name: 'Frenkie de Jong', pos: 'MID' },
    { name: 'Virgil van Dijk', pos: 'DEF' },
    { name: 'Daley Blind', pos: 'DEF' },
    { name: 'Denzel Dumfries', pos: 'DEF' },
    { name: 'Steven Bergwijn', pos: 'FWD' },
    { name: 'Tijjani Reijnders', pos: 'MID' },
    { name: 'Bart Verbruggen', pos: 'GK' },
  ],
  'Belgia': [
    { name: 'Romelu Lukaku', pos: 'FWD' },
    { name: 'Kevin De Bruyne', pos: 'MID' },
    { name: 'Eden Hazard', pos: 'FWD' },
    { name: 'Yannick Carrasco', pos: 'FWD' },
    { name: 'Axel Witsel', pos: 'MID' },
    { name: 'Toby Alderweireld', pos: 'DEF' },
    { name: 'Jan Vertonghen', pos: 'DEF' },
    { name: 'Leandro Trossard', pos: 'FWD' },
    { name: 'Jeremy Doku', pos: 'FWD' },
    { name: 'Thibaut Courtois', pos: 'GK' },
  ],
  'Uruguay': [
    { name: 'Darwin Núñez', pos: 'FWD' },
    { name: 'Luis Suárez', pos: 'FWD' },
    { name: 'Federico Valverde', pos: 'MID' },
    { name: 'Rodrigo Bentancur', pos: 'MID' },
    { name: 'Facundo Pellistri', pos: 'FWD' },
    { name: 'José María Giménez', pos: 'DEF' },
    { name: 'Diego Godín', pos: 'DEF' },
    { name: 'Ronald Araújo', pos: 'DEF' },
    { name: 'Sergio Rochet', pos: 'GK' },
  ],
  'Mexico': [
    { name: 'Hirving Lozano', pos: 'FWD' },
    { name: 'Raúl Jiménez', pos: 'FWD' },
    { name: 'Alexis Vega', pos: 'FWD' },
    { name: 'Héctor Herrera', pos: 'MID' },
    { name: 'Andrés Guardado', pos: 'MID' },
    { name: 'Carlos Vela', pos: 'FWD' },
    { name: 'César Montes', pos: 'DEF' },
    { name: 'Guillermo Ochoa', pos: 'GK' },
  ],
  'USA': [
    { name: 'Christian Pulisic', pos: 'FWD' },
    { name: 'Gio Reyna', pos: 'MID' },
    { name: 'Tyler Adams', pos: 'MID' },
    { name: 'Weston McKennie', pos: 'MID' },
    { name: 'Josh Sargent', pos: 'FWD' },
    { name: 'Ricardo Pepi', pos: 'FWD' },
    { name: 'Antonee Robinson', pos: 'DEF' },
    { name: 'Matt Turner', pos: 'GK' },
  ],
  'Canada': [
    { name: 'Alphonso Davies', pos: 'DEF' },
    { name: 'Jonathan David', pos: 'FWD' },
    { name: 'Cyle Larin', pos: 'FWD' },
    { name: 'Tajon Buchanan', pos: 'FWD' },
    { name: 'Stephen Eustáquio', pos: 'MID' },
    { name: 'Atiba Hutchinson', pos: 'MID' },
    { name: 'Milan Borjan', pos: 'GK' },
  ],
  'Senegal': [
    { name: 'Sadio Mané', pos: 'FWD' },
    { name: 'Kalidou Koulibaly', pos: 'DEF' },
    { name: 'Idrissa Gueye', pos: 'MID' },
    { name: 'Ismaïla Sarr', pos: 'FWD' },
    { name: 'Cheikhou Kouyaté', pos: 'MID' },
    { name: 'Bamba Dieng', pos: 'FWD' },
    { name: 'Édouard Mendy', pos: 'GK' },
  ],
  'Marokko': [
    { name: 'Hakim Ziyech', pos: 'MID' },
    { name: 'Youssef En-Nesyri', pos: 'FWD' },
    { name: 'Achraf Hakimi', pos: 'DEF' },
    { name: 'Sofyan Amrabat', pos: 'MID' },
    { name: 'Romain Saïss', pos: 'DEF' },
    { name: 'Noussair Mazraoui', pos: 'DEF' },
    { name: 'Azzedine Ounahi', pos: 'MID' },
    { name: 'Yassine Bounou', pos: 'GK' },
  ],
  'Japan': [
    { name: 'Takumi Minamino', pos: 'FWD' },
    { name: 'Daichi Kamada', pos: 'MID' },
    { name: 'Ritsu Doan', pos: 'MID' },
    { name: 'Kaoru Mitoma', pos: 'FWD' },
    { name: 'Wataru Endo', pos: 'MID' },
    { name: 'Hiroki Sakai', pos: 'DEF' },
    { name: 'Shuichi Gonda', pos: 'GK' },
  ],
  'Sør-Korea': [
    { name: 'Son Heung-min', pos: 'FWD' },
    { name: 'Lee Jae-sung', pos: 'MID' },
    { name: 'Hwang Hee-chan', pos: 'FWD' },
    { name: 'Kim Min-jae', pos: 'DEF' },
    { name: 'Jung Woo-young', pos: 'MID' },
    { name: 'Kim Seung-gyu', pos: 'GK' },
  ],
  'Kroatia': [
    { name: 'Luka Modrić', pos: 'MID' },
    { name: 'Ivan Perišić', pos: 'FWD' },
    { name: 'Marcelo Brozović', pos: 'MID' },
    { name: 'Mateo Kovačić', pos: 'MID' },
    { name: 'Ante Rebić', pos: 'FWD' },
    { name: 'Dejan Lovren', pos: 'DEF' },
    { name: 'Dominik Livaković', pos: 'GK' },
  ],
  'Sveits': [
    { name: 'Xherdan Shaqiri', pos: 'FWD' },
    { name: 'Granit Xhaka', pos: 'MID' },
    { name: 'Haris Seferović', pos: 'FWD' },
    { name: 'Breel Embolo', pos: 'FWD' },
    { name: 'Denis Zakaria', pos: 'MID' },
    { name: 'Yann Sommer', pos: 'GK' },
  ],
  'Danmark': [
    { name: 'Christian Eriksen', pos: 'MID' },
    { name: 'Martin Braithwaite', pos: 'FWD' },
    { name: 'Pierre-Emile Højbjerg', pos: 'MID' },
    { name: 'Kasper Dolberg', pos: 'FWD' },
    { name: 'Simon Kjær', pos: 'DEF' },
    { name: 'Kasper Schmeichel', pos: 'GK' },
  ],
  'Østerrike': [
    { name: 'Marko Arnautović', pos: 'FWD' },
    { name: 'David Alaba', pos: 'DEF' },
    { name: 'Marcel Sabitzer', pos: 'MID' },
    { name: 'Christoph Baumgartner', pos: 'MID' },
    { name: 'Patrick Wimmer', pos: 'MID' },
    { name: 'Patrick Pentz', pos: 'GK' },
  ],
  'Iran': [
    { name: 'Mehdi Taremi', pos: 'FWD' },
    { name: 'Sardar Azmoun', pos: 'FWD' },
    { name: 'Alireza Jahanbakhsh', pos: 'FWD' },
    { name: 'Ali Gholizadeh', pos: 'MID' },
    { name: 'Alireza Beiranvand', pos: 'GK' },
  ],
  'Saudi-Arabia': [
    { name: 'Salem Al-Dawsari', pos: 'FWD' },
    { name: 'Saleh Al-Shehri', pos: 'FWD' },
    { name: 'Mohammed Al-Owais', pos: 'GK' },
    { name: 'Ali Al-Bulayhi', pos: 'DEF' },
  ],
  'Ghana': [
    { name: 'Jordan Ayew', pos: 'FWD' },
    { name: 'André Ayew', pos: 'FWD' },
    { name: 'Thomas Partey', pos: 'MID' },
    { name: 'Mohammed Kudus', pos: 'MID' },
    { name: 'Lawrence Ati Zigi', pos: 'GK' },
  ],
  'Ecuador': [
    { name: 'Enner Valencia', pos: 'FWD' },
    { name: 'Moisés Caicedo', pos: 'MID' },
    { name: 'Gonzalo Plata', pos: 'FWD' },
    { name: 'Piero Hincapié', pos: 'DEF' },
    { name: 'Hernán Galíndez', pos: 'GK' },
  ],
  'Colombia': [
    { name: 'James Rodríguez', pos: 'MID' },
    { name: 'Radamel Falcao', pos: 'FWD' },
    { name: 'Luis Díaz', pos: 'FWD' },
    { name: 'Juan Cuadrado', pos: 'MID' },
    { name: 'Davinson Sánchez', pos: 'DEF' },
    { name: 'David Ospina', pos: 'GK' },
  ],
  'Tunisia': [
    { name: 'Wahbi Khazri', pos: 'FWD' },
    { name: 'Youssef Msakni', pos: 'FWD' },
    { name: 'Ellyes Skhiri', pos: 'MID' },
    { name: 'Aymen Dahmen', pos: 'GK' },
  ],
  'Egypt': [
    { name: 'Mohamed Salah', pos: 'FWD' },
    { name: 'Mostafa Mohamed', pos: 'FWD' },
    { name: 'Mohamed Elneny', pos: 'MID' },
    { name: 'Mohamed Abdelmonem', pos: 'DEF' },
    { name: 'Mohamed El-Shenawy', pos: 'GK' },
  ],
  'Nigeria': [
    { name: 'Victor Osimhen', pos: 'FWD' },
    { name: 'Kelechi Iheanacho', pos: 'FWD' },
    { name: 'Wilfred Ndidi', pos: 'MID' },
    { name: 'Alex Iwobi', pos: 'MID' },
    { name: 'Francis Uzoho', pos: 'GK' },
  ],
  'Norge': [
    { name: 'Erling Haaland', pos: 'FWD' },
    { name: 'Martin Ødegaard', pos: 'MID' },
    { name: 'Alexander Sørloth', pos: 'FWD' },
    { name: 'Sander Berge', pos: 'MID' },
    { name: 'Kristian Thorstvedt', pos: 'MID' },
    { name: 'Leo Østigård', pos: 'DEF' },
    { name: 'Ørjan Nyland', pos: 'GK' },
  ],
  'Sverige': [
    { name: 'Zlatan Ibrahimović', pos: 'FWD' },
    { name: 'Alexander Isak', pos: 'FWD' },
    { name: 'Dejan Kulusevski', pos: 'MID' },
    { name: 'Emil Forsberg', pos: 'MID' },
    { name: 'Victor Lindelöf', pos: 'DEF' },
    { name: 'Robin Olsen', pos: 'GK' },
  ],
  'Skottland': [
    { name: 'Andrew Robertson', pos: 'DEF' },
    { name: 'Scott McTominay', pos: 'MID' },
    { name: 'Che Adams', pos: 'FWD' },
    { name: 'John McGinn', pos: 'MID' },
    { name: 'Craig Gordon', pos: 'GK' },
  ],
  'Tyrkia': [
    { name: 'Hakan Çalhanoğlu', pos: 'MID' },
    { name: 'Burak Yılmaz', pos: 'FWD' },
    { name: 'Arda Güler', pos: 'MID' },
    { name: 'Yusuf Yazıcı', pos: 'MID' },
    { name: 'Merih Demiral', pos: 'DEF' },
    { name: 'Uğurcan Çakır', pos: 'GK' },
  ],
  'Australia': [
    { name: 'Mathew Leckie', pos: 'FWD' },
    { name: 'Mitchell Duke', pos: 'FWD' },
    { name: 'Aaron Mooy', pos: 'MID' },
    { name: 'Riley McGree', pos: 'MID' },
    { name: 'Mat Ryan', pos: 'GK' },
  ],
  'Paraguay': [
    { name: 'Miguel Almirón', pos: 'MID' },
    { name: 'Ángel Romero', pos: 'FWD' },
    { name: 'Gustavo Gómez', pos: 'DEF' },
    { name: 'Antony Silva', pos: 'GK' },
  ],
  'Irak': [
    { name: 'Mohanad Ali', pos: 'FWD' },
    { name: 'Amjed Attwan', pos: 'MID' },
    { name: 'Jalal Hassan', pos: 'GK' },
  ],
  'Algerie': [
    { name: 'Riyad Mahrez', pos: 'FWD' },
    { name: 'Islam Slimani', pos: 'FWD' },
    { name: 'Sofiane Feghouli', pos: 'MID' },
    { name: 'Samir Handanović', pos: 'GK' },
  ],
  'Jordan': [
    { name: 'Musa Al-Taamari', pos: 'FWD' },
    { name: 'Ahmad Ercan', pos: 'MID' },
    { name: 'Yazan Al-Naimat', pos: 'GK' },
  ],
  'Kongo DR': [
    { name: 'Cédric Bakambu', pos: 'FWD' },
    { name: 'Yannick Bolasie', pos: 'FWD' },
    { name: 'Chancel Mbemba', pos: 'DEF' },
    { name: 'Ivi López', pos: 'GK' },
  ],
  'Usbekistan': [
    { name: 'Eldor Shomurodov', pos: 'FWD' },
    { name: 'Jaloliddin Masharipov', pos: 'MID' },
    { name: 'Otabek Shukurov', pos: 'GK' },
  ],
  'Kapp Verde': [
    { name: 'Ryan Mendes', pos: 'FWD' },
    { name: 'Garry Rodrigues', pos: 'FWD' },
    { name: 'Lisandro Semedo', pos: 'GK' },
  ],
  'New Zealand': [
    { name: 'Chris Wood', pos: 'FWD' },
    { name: 'Ryan Thomas', pos: 'MID' },
    { name: 'Stefan Marinovic', pos: 'GK' },
  ],
  'Tsjekkia': [
    { name: 'Patrik Schick', pos: 'FWD' },
    { name: 'Tomáš Souček', pos: 'MID' },
    { name: 'Vladimír Coufal', pos: 'DEF' },
    { name: 'Jakub Brabec', pos: 'DEF' },
    { name: 'Jiří Pavlenka', pos: 'GK' },
  ],
  'Elfenbenskysten': [
    { name: 'Sébastien Haller', pos: 'FWD' },
    { name: 'Nicolas Pépé', pos: 'FWD' },
    { name: 'Franck Kessié', pos: 'MID' },
    { name: 'Jean-Philippe Krasso', pos: 'FWD' },
    { name: 'Yahia Fofana', pos: 'GK' },
  ],
  'Sør-Afrika': [
    { name: 'Percy Tau', pos: 'FWD' },
    { name: 'Lyle Foster', pos: 'FWD' },
    { name: 'Themba Zwane', pos: 'MID' },
    { name: 'Ronwen Williams', pos: 'GK' },
  ],
  'Qatar': [
    { name: 'Akram Afif', pos: 'FWD' },
    { name: 'Almoez Ali', pos: 'FWD' },
    { name: 'Hassan Al-Haydos', pos: 'MID' },
    { name: 'Meshaal Barsham', pos: 'GK' },
  ],
  'Bosnia-Herz': [
    { name: 'Edin Džeko', pos: 'FWD' },
    { name: 'Miralem Pjanić', pos: 'MID' },
    { name: 'Sead Kolašinac', pos: 'DEF' },
    { name: 'Ibrahim Šehić', pos: 'GK' },
  ],
  'Haiti': [
    { name: 'Duckens Nazon', pos: 'FWD' },
    { name: 'Frantzdy Pierrot', pos: 'FWD' },
    { name: 'Hervé Bazile', pos: 'MID' },
    { name: 'Josué Duverger', pos: 'GK' },
  ],
  'Curacao': [
    { name: 'Cuco Martina', pos: 'DEF' },
    { name: 'Leandro Bacuna', pos: 'MID' },
    { name: 'Elson Hooi', pos: 'FWD' },
    { name: 'Eloy Room', pos: 'GK' },
  ],
  'Panama': [
    { name: 'Rolando Blackburn', pos: 'FWD' },
    { name: 'Gabriel Torres', pos: 'FWD' },
    { name: 'Andrés Andrade', pos: 'MID' },
    { name: 'Luis Mejía', pos: 'GK' },
  ],
};

// Flat liste over alle spillere for autocomplete
export const ALL_PLAYERS = Object.entries(SQUADS).flatMap(([team, players]) =>
  players.map(p => ({ ...p, team }))
);

// Søkefunksjon med fuzzy matching (ignorerer aksenter og store/små bokstaver)
function normalize(str) {
  return str.normalize('NFD').replace(/[\u0300-\u036f]/g, '').toLowerCase();
}

export function searchPlayers(query, limit = 8) {
  if (!query || query.length < 2) return [];
  const q = normalize(query);
  return ALL_PLAYERS
    .filter(p => normalize(p.name).includes(q) || normalize(p.team).includes(q))
    .slice(0, limit);
}
