export const C = {
  app: { minHeight:'100vh', background:'#0a0a0a', fontFamily:"'DM Sans',sans-serif", color:'#f0f0f0', fontSize:16, overflowX:'hidden' },
  hdr: { background:'#0a0a0a', borderBottom:'3px solid #ff6b00', position:'sticky', top:0, zIndex:100, boxShadow:'0 4px 40px rgba(255,107,0,.15)' },
  hdrInner: { display:'flex', alignItems:'center', justifyContent:'space-between', padding:'12px 24px', flexWrap:'wrap', gap:8 },
  logo: { display:'flex', alignItems:'center', gap:14 },
  ball: { fontSize:38, lineHeight:1, filter:'drop-shadow(0 0 12px rgba(255,107,0,.8))' },
  ltitle: { fontFamily:"'Archivo Black',sans-serif", fontSize:26, color:'#ff6b00', letterSpacing:1, lineHeight:1, textTransform:'uppercase' },
  lsub: { fontSize:9, color:'#444', letterSpacing:3, textTransform:'uppercase', marginTop:3, fontFamily:"'Fira Code',monospace" },
  userChip: { fontSize:12, color:'#ff6b00', background:'rgba(255,107,0,.08)', border:'1px solid rgba(255,107,0,.25)', borderRadius:20, padding:'5px 14px', fontFamily:"'Fira Code',monospace" },
  btnOut: { background:'transparent', border:'1px solid #222', color:'#555', borderRadius:6, padding:'5px 14px', cursor:'pointer', fontSize:13, fontFamily:'inherit' },
  winBanner: { textAlign:'center', padding:'8px 16px', fontSize:12, fontFamily:"'Fira Code',monospace", letterSpacing:1, transition:'background .5s', borderTop:'1px solid #111' },
  nav: { display:'flex', overflowX:'auto', padding:'0 12px', gap:2 },
  navBtn: { background:'transparent', border:'none', color:'#444', padding:'10px 16px', cursor:'pointer', fontFamily:"'DM Sans',sans-serif", borderBottom:'3px solid transparent', transition:'all .2s', display:'flex', flexDirection:'column', alignItems:'center', gap:2, whiteSpace:'nowrap', fontSize:11, fontWeight:700, textTransform:'uppercase', letterSpacing:1 },
  navOn: { color:'#ff6b00', borderBottomColor:'#ff6b00' },
  main: { maxWidth:920, margin:'0 auto', padding:'28px 16px' },
  footer: { textAlign:'center', padding:'28px', color:'#222', fontSize:11, borderTop:'1px solid #111', fontFamily:"'Fira Code',monospace", letterSpacing:1 },

  card: { background:'#111', border:'1px solid #1a1a1a', borderRadius:16, padding:24, marginBottom:20, position:'relative', overflow:'hidden' },
  cardH: { fontFamily:"'Archivo Black',sans-serif", fontSize:22, color:'#fff', letterSpacing:.5, marginBottom:20, textTransform:'uppercase' },
  secH: { fontFamily:"'Fira Code',monospace", fontSize:10, color:'#444', textTransform:'uppercase', letterSpacing:3, display:'block', marginBottom:10 },
  mono12: { fontSize:11, color:'#444', fontFamily:"'Fira Code',monospace" },
  row: { display:'flex', alignItems:'center', gap:12, marginBottom:16, flexWrap:'wrap' },

  authWrap: { minHeight:'100vh', display:'flex', alignItems:'center', justifyContent:'center', background:'#0a0a0a', padding:16, position:'relative' },
  authBg: { position:'fixed', inset:0, zIndex:0, pointerEvents:'none', background:'radial-gradient(ellipse 60% 40% at 20% 20%,rgba(255,107,0,.1) 0%,transparent 60%), radial-gradient(ellipse 50% 40% at 80% 80%,rgba(0,200,83,.07) 0%,transparent 60%)' },
  authBox: { position:'relative', zIndex:1, background:'#111', border:'1px solid #1e1e1e', borderRadius:20, padding:'48px 40px', width:'100%', maxWidth:440, boxShadow:'0 0 100px rgba(255,107,0,.08)' },
  authBall: { fontSize:80, textAlign:'center', marginBottom:8, display:'block', filter:'drop-shadow(0 0 30px rgba(255,107,0,.5))' },
  authTitle: { fontFamily:"'Archivo Black',sans-serif", fontSize:32, textAlign:'center', color:'#fff', letterSpacing:2, marginBottom:4, textTransform:'uppercase' },
  authSub: { color:'#333', textAlign:'center', fontSize:10, letterSpacing:3, textTransform:'uppercase', marginBottom:32, fontFamily:"'Fira Code',monospace" },

  inp: { width:'100%', background:'#0a0a0a', border:'1px solid #1e1e1e', borderRadius:10, color:'#f0f0f0', padding:'12px 16px', fontSize:15, marginBottom:12, fontFamily:"'DM Sans',sans-serif", outline:'none' },
  sel: { background:'#0a0a0a', border:'1px solid #1e1e1e', borderRadius:8, color:'#f0f0f0', padding:'8px 12px', fontSize:14, fontFamily:"'DM Sans',sans-serif", cursor:'pointer' },
  ta: { width:'100%', background:'#0a0a0a', border:'1px solid #1e1e1e', borderRadius:10, color:'#f0f0f0', padding:'12px 14px', fontSize:12, fontFamily:"'Fira Code',monospace", resize:'vertical', outline:'none' },
  btnGold: { width:'100%', background:'linear-gradient(135deg,#ff6b00,#e55a00)', color:'#fff', border:'none', borderRadius:10, padding:'13px 24px', fontWeight:700, fontSize:14, cursor:'pointer', fontFamily:"'Archivo Black',sans-serif", letterSpacing:2, display:'block', transition:'all .2s', textTransform:'uppercase', boxShadow:'0 4px 20px rgba(255,107,0,.25)' },
  btnSm: { background:'transparent', border:'1px solid #222', color:'#555', borderRadius:6, padding:'5px 12px', cursor:'pointer', fontSize:12, fontFamily:'inherit' },
  err: { color:'#ff4444', fontSize:13, textAlign:'center', marginBottom:10, fontFamily:"'Fira Code',monospace" },

  tabs: { display:'flex', borderBottom:'1px solid #1a1a1a', marginBottom:20 },
  tab: { flex:1, background:'transparent', border:'none', borderBottom:'3px solid transparent', color:'#444', padding:'10px', cursor:'pointer', fontSize:12, fontFamily:"'DM Sans',sans-serif", fontWeight:700, transition:'all .2s', textTransform:'uppercase', letterSpacing:1 },
  tabOn: { color:'#ff6b00', borderBottomColor:'#ff6b00' },

  gTabs: { display:'flex', flexWrap:'wrap', gap:6, marginBottom:16 },
  gTab: { background:'transparent', border:'1px solid #1e1e1e', color:'#444', borderRadius:8, padding:'5px 13px', cursor:'pointer', fontSize:12, fontFamily:"'Fira Code',monospace", transition:'all .2s' },
  gTabOn: { background:'rgba(255,107,0,.12)', color:'#ff6b00', borderColor:'rgba(255,107,0,.5)', fontWeight:700 },

  matchList: { display:'flex', flexDirection:'column', gap:4 },
  mRow: { display:'flex', alignItems:'center', gap:8, padding:'8px 12px', borderRadius:8, background:'#0d0d0d', flexWrap:'wrap' },
  mDate: { fontSize:10, color:'#2a2a2a', fontFamily:"'Fira Code',monospace", minWidth:44 },
  mTeam: { fontSize:14, flex:1, minWidth:90, fontWeight:500 },
  sInp: { width:50, background:'#0a0a0a', border:'1px solid #2a2a2a', borderRadius:8, color:'#ff6b00', padding:'7px 4px', fontSize:18, textAlign:'center', fontWeight:700, fontFamily:"'Fira Code',monospace", outline:'none' },
  dash: { color:'#2a2a2a', fontWeight:700, fontSize:18 },

  plRow: { display:'flex', alignItems:'center', gap:10, marginBottom:8 },
  plPos: { color:'#ff6b00', fontWeight:700, width:24, fontFamily:"'Fira Code',monospace" },

  specBox: { background:'#0d0d0d', borderRadius:12, padding:16, marginBottom:20, border:'1px solid #1a1a1a' },
  specRow: { display:'flex', alignItems:'center', gap:10, padding:'8px 0', borderBottom:'1px solid #111', flexWrap:'wrap' },
  specLabel: { fontSize:14, color:'#888', minWidth:190, fontWeight:500 },
  ptsBadge: { fontFamily:"'Fira Code',monospace", fontSize:10, color:'#00c853', background:'rgba(0,200,83,.1)', border:'1px solid rgba(0,200,83,.2)', borderRadius:4, padding:'2px 7px' },

  badge: { fontSize:11, borderRadius:20, padding:'4px 12px', letterSpacing:1, textTransform:'uppercase', fontWeight:700, fontFamily:"'Fira Code',monospace", display:'inline-block' },
  youTag: { fontSize:10, color:'#ff6b00', fontFamily:"'Fira Code',monospace", background:'rgba(255,107,0,.1)', borderRadius:4, padding:'1px 6px', marginLeft:6 },
  wonBadge: { fontSize:11, background:'rgba(0,200,83,.1)', color:'#00c853', border:'1px solid rgba(0,200,83,.2)', borderRadius:4, padding:'2px 8px', fontFamily:"'Fira Code',monospace" },

  lbRow: { display:'flex', alignItems:'center', gap:14, padding:'14px 18px', borderRadius:12, marginBottom:6, background:'#0d0d0d', border:'1px solid transparent', transition:'all .2s' },
  lbMe: { background:'rgba(255,107,0,.05)', border:'1px solid rgba(255,107,0,.2)' },
  lbRank: { fontSize:24, width:36, textAlign:'center' },
  lbName: { flex:1, fontWeight:600, fontSize:16 },
  lbPts: { fontFamily:"'Archivo Black',sans-serif", fontSize:32, color:'#ff6b00', letterSpacing:1, lineHeight:1 },
  lbPtsL: { fontSize:9, color:'#333', fontFamily:"'Fira Code',monospace", textTransform:'uppercase', letterSpacing:2, textAlign:'right' },

  scoreBox: { background:'#0d0d0d', borderRadius:14, padding:22, textAlign:'center', border:'1px solid #1a1a1a' },
  scoreNum: { fontFamily:"'Archivo Black',sans-serif", fontSize:52, letterSpacing:1, lineHeight:1 },
  scoreL: { fontSize:10, color:'#444', marginTop:8, fontFamily:"'Fira Code',monospace", textTransform:'uppercase', letterSpacing:2 },

  chatBox: { height:340, overflowY:'auto', background:'#0d0d0d', borderRadius:14, padding:16, marginBottom:12, border:'1px solid #1a1a1a', display:'flex', flexDirection:'column', gap:10 },

  phBtn: { display:'block', width:'100%', background:'transparent', border:'1px solid #1a1a1a', color:'#444', borderRadius:8, padding:'10px 16px', marginBottom:5, cursor:'pointer', textAlign:'left', fontSize:13, fontFamily:'inherit', transition:'all .2s' },
  phBtnOn: { background:'rgba(255,107,0,.1)', color:'#ff6b00', borderColor:'rgba(255,107,0,.4)', fontWeight:700 },
  roundL: { fontFamily:"'Fira Code',monospace", fontSize:10, color:'#ff6b00', textTransform:'uppercase', letterSpacing:3, marginBottom:10, display:'block' },

  lockBanner: { background:'rgba(255,68,68,.06)', border:'1px solid rgba(255,68,68,.15)', borderRadius:10, padding:'12px 16px', marginBottom:16, color:'#ff6666', fontSize:14 },
  infoBox: { background:'#0d0d0d', border:'1px solid #1a1a1a', borderRadius:12, padding:22, marginTop:8 },
  spinner: { display:'inline-block', animation:'spin 1s linear infinite' },
};
